ALTER TABLE strava_activities
ADD COLUMN IF NOT EXISTS max_speed FLOAT,
ADD COLUMN IF NOT EXISTS selected BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS visible BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS coordinates FLOAT[],
ADD COLUMN IF NOT EXISTS bounds FLOAT[][],
ADD COLUMN IF NOT EXISTS feature JSONB,
ADD COLUMN IF NOT EXISTS source_id TEXT,
ADD COLUMN IF NOT EXISTS layer_id TEXT,
ADD COLUMN IF NOT EXISTS geometry JSONB; 